# Generated by Django 3.2.3 on 2021-05-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
    ]
