# Generated by Django 3.2.3 on 2021-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('Fecha_de_emision', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Precio_costo', models.CharField(max_length=100)),
                ('Precio_venta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('Nombre_de_producto', models.CharField(max_length=50)),
                ('Cantidad_de_producto', models.CharField(max_length=100)),
                ('Precio_costo', models.CharField(max_length=100)),
                ('Precio_venta', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_de_Inventario',
            fields=[
                ('Productos', models.CharField(max_length=50)),
                ('Precio_costo', models.CharField(max_length=100)),
                ('Precio_venta', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('Nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('edad', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='edad',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
